import type { ClassDBItem } from "./classes";

export const DB_ALL: ClassDBItem[] = [
  {
    id: 1,
    label: "2x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "cilindro"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 125,
      },
      prices_qtts: {
        "1": 125,
        "25": 120,
        "50": 105,
        "100": 90,
        "500": 85,
        "1000": 80,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 2,
      alto: 2,
      peso: 0.15,
      fuerzaExp: 0.14,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N40",
    },
  },
  {
    id: 2,
    label: "2x4mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "cilindro"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 140,
      },
      prices_qtts: {
        "1": 140,
        "25": 130,
        "50": 115,
        "100": 100,
        "500": 95,
        "1000": 90,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 2,
      alto: 4,
      peso: 0.35,
      fuerzaExp: 0.12,
    },
    isComparable: true,
  },
  {
    id: 3,
    label: "3x1mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 120,
      },
      prices_qtts: {
        "1": 120,
        "25": 115,
        "50": 100,
        "100": 85,
        "500": 80,
        "1000": 75,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 3,
      alto: 1,
      peso: 0.2,
      fuerzaExp: 0.1,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N38",
    },
  },
  {
    id: 4,
    label: "3x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "boton"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 135,
      },
      prices_qtts: {
        "1": 135,
        "25": 130,
        "50": 115,
        "100": 100,
        "500": 95,
        "1000": 90,
      },
      update: "20/8/2025",
    },
    measures: {
      largo: 3,
      alto: 2,
      peso: 0.2,
      fuerzaExp: 0.19,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N40",
    },
  },
  {
    id: 5,
    label: "4x1mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 130,
      },
      prices_qtts: {
        "1": 130,
        "25": 125,
        "50": 110,
        "100": 95,
        "500": 90,
        "1000": 85,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 4,
      alto: 1,
      peso: 0.25,
      fuerzaExp: 0.27,
    },
    isComparable: true,
  },
  {
    id: 6,
    label: "4x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 140,
      },
      prices_qtts: {
        "1": 140,
        "25": 130,
        "50": 115,
        "100": 100,
        "500": 95,
        "1000": 90,
      },
      update: "20/8/2025",
    },
    measures: {
      largo: 4,
      alto: 2,
      peso: 0.25,
      fuerzaExp: 0.4,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N40",
    },
  },
  {
    id: 7,
    label: "5x1mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 140,
      },
      prices_qtts: {
        "1": 140,
        "25": 130,
        "50": 115,
        "100": 100,
        "500": 95,
        "1000": 90,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 5,
      alto: 1,
      peso: 0.25,
      fuerzaExp: 0.4,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N38",
    },
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo/up/MLAU2990934691",
    },
  },
  {
    id: 8,
    label: "5x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 145,
      },
      prices_qtts: {
        "1": 145,
        "25": 140,
        "50": 125,
        "100": 105,
        "500": 100,
        "1000": 95,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 5,
      alto: 2,
      peso: 0.3,
      fuerzaExp: 0.6,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N38",
    },
  },
  {
    id: 9,
    label: "5x4mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "boton"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 205,
      },
      prices_qtts: {
        "1": 205,
        "25": 195,
        "50": 170,
        "100": 150,
        "500": 140,
        "1000": 130,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 5,
      alto: 4,
      peso: 0.6,
      fuerzaExp: 0.84,
    },
    isComparable: true,
  },
  {
    noStock: true,
    id: 10,
    label: "5x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "cilindro"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 265,
      },
      prices_qtts: {
        "1": 265,
        "25": 250,
        "50": 220,
        "100": 190,
        "500": 180,
        "1000": 170,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 5,
      alto: 5,
      peso: 0.7,
    },
    isComparable: true,
  },
  {
    id: 11,
    label: "6x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 245,
      },
      prices_qtts: {
        "1": 245,
        "25": 230,
        "50": 205,
        "100": 180,
        "500": 170,
        "1000": 160,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 6,
      alto: 3,
      peso: 0.65,
      fuerzaExp: 0.82,
    },
    isComparable: true,
  },
  {
    id: 12,
    label: "7x1.5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 185,
      },
      prices_qtts: {
        "1": 185,
        "25": 175,
        "50": 155,
        "100": 135,
        "500": 125,
        "1000": 115,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 7,
      alto: 1.5,
      peso: 0.5,
      fuerzaExp: 0.45,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo/up/MLAU2990936401",
    },
  },
  {
    id: 13,
    label: "7x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "boton"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 560,
      },
      prices_qtts: {
        "1": 560,
        "25": 530,
        "50": 470,
        "100": 410,
        "250": 385,
        "500": 360,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 7,
      alto: 5,
      peso: 1.6,
      fuerzaExp: 1.2,
    },
    isComparable: true,
  },
  {
    id: 14,
    label: "8x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 385,
      },
      prices_qtts: {
        "1": 385,
        "25": 360,
        "50": 320,
        "100": 280,
        "500": 260,
        "1000": 245,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 8,
      alto: 3,
      peso: 1.3,
      fuerzaExp: 1.6,
    },
    especificaciones: {
      denominación: "N42",
    },
    isComparable: true,
  },
  {
    id: 15,
    label: "8x4mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 510,
      },
      prices_qtts: {
        "1": 510,
        "25": 480,
        "50": 425,
        "100": 370,
        "500": 345,
        "1000": 325,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 8,
      alto: 4,
      peso: 1.6,
      fuerzaExp: 1.7,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N42",
    },
  },
  {
    id: 16,
    label: "8x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "boton"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 530,
      },
      prices_qtts: {
        "1": 530,
        "25": 500,
        "50": 440,
        "100": 380,
        "500": 360,
        "1000": 340,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 8,
      alto: 5,
      peso: 1.9,
      fuerzaExp: 1.8,
    },
    isComparable: true,
  },
  {
    id: 17,
    label: "9x1.5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 325,
      },
      prices_qtts: {
        "1": 325,
        "25": 305,
        "50": 270,
        "100": 235,
        "500": 220,
        "1000": 210,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 9,
      alto: 1.5,
      peso: 0.75,
      fuerzaExp: 0.72,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N46",
    },
  },
  {
    id: 18,
    label: "9x2.5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 390,
      },
      prices_qtts: {
        "1": 390,
        "25": 370,
        "50": 330,
        "100": 285,
        "500": 270,
        "1000": 250,
      },
      update: "20/8/2025",
    },
    measures: {
      largo: 9,
      alto: 2.5,
      peso: 1.25,
      fuerzaExp: 1.2,
    },
    especificaciones: {
      denominación: "N42",
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo/up/MLAU2996280676",
    },
  },
  {
    id: 19,
    label: "10x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 500,
      },
      prices_qtts: {
        "1": 500,
        "25": 475,
        "50": 420,
        "100": 365,
        "500": 340,
        "1000": 320,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 10,
      alto: 2,
      peso: 1.5,
      fuerzaExp: 1.13,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N40",
    },
  },
  {
    id: 20,
    label: "10x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 600,
      },
      prices_qtts: {
        "1": 600,
        "25": 570,
        "50": 500,
        "100": 435,
        "250": 410,
        "500": 385,
      },
      update: "20/8/2025",
    },
    measures: {
      largo: 10,
      alto: 3,
      peso: 1.75,
      fuerzaExp: 1.7,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N42",
    },
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo/up/MLAU2991085903",
    },
  },
  {
    id: 21,
    label: "10x4mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 800,
      },
      prices_qtts: {
        "1": 800,
        "25": 750,
        "50": 670,
        "100": 580,
        "250": 540,
        "500": 510,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 10,
      alto: 4,
      peso: 2.4,
      fuerzaExp: 2,
    },
    isComparable: true,
  },
  {
    id: 22,
    label: "10x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 900,
      },
      prices_qtts: {
        "1": 900,
        "25": 850,
        "50": 750,
        "100": 650,
        "250": 610,
        "500": 570,
      },
      update: "20/8/2025",
    },
    measures: {
      largo: 10,
      alto: 5,
      peso: 3,
      fuerzaExp: 3,
    },
    isComparable: true,
  },
  {
    noStock: true,
    id: 23,
    label: "10x10mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "cilindro"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1230,
      },
      prices_qtts: {
        "1": 1230,
        "20": 1170,
        "40": 1030,
        "80": 890,
        "200": 840,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 10,
      alto: 10,
      peso: 6,
      fuerzaExp: 3.4,
    },
    isComparable: true,
  },
  {
    id: 24,
    label: "10x20mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "cilindro"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 2150,
      },
      prices_qtts: {
        "1": 2150,
        "10": 2050,
        "25": 1850,
        "50": 1650,
        "120": 1550,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 10,
      alto: 20,
      peso: 12,
      fuerzaExp: 3.4,
    },
    isComparable: true,
  },
  {
    id: 25,
    label: "11x4mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 860,
      },
      prices_qtts: {
        "1": 860,
        "25": 810,
        "50": 720,
        "100": 620,
        "250": 590,
        "500": 550,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 11,
      alto: 4,
      peso: 3,
      fuerzaExp: 1.6,
    },
    isComparable: true,
  },
  {
    id: 26,
    label: "11x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 970,
      },
      prices_qtts: {
        "1": 970,
        "20": 920,
        "40": 810,
        "80": 710,
        "200": 670,
      },
      update: "20/8/2025",
    },
    measures: {
      largo: 11,
      alto: 5,
      peso: 3.6,
      fuerzaExp: 2.1,
    },
    isComparable: true,
  },
  {
    id: 27,
    label: "12x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 860,
      },
      prices_qtts: {
        "1": 860,
        "25": 810,
        "50": 720,
        "100": 620,
        "250": 590,
        "500": 550,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 12,
      alto: 3,
      peso: 2.6,
      fuerzaExp: 3,
    },
    isComparable: true,
  },
  {
    id: 28,
    label: "12x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1070,
      },
      prices_qtts: {
        "1": 1070,
        "20": 1010,
        "40": 900,
        "80": 780,
        "200": 730,
      },
      update: "28/8/2025",
    },
    measures: {
      largo: 12,
      alto: 5,
      peso: 4.3,
      fuerzaExp: 3.6,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo/up/MLAU2996280680",
    },
  },
  {
    id: 29,
    label: "15x2mm N35",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 730,
      },
      prices_qtts: {
        "1": 730,
        "25": 690,
        "50": 610,
        "100": 530,
        "500": 495,
        "1000": 465,
      },
      update: "21/4",
    },
    measures: {
      largo: 15,
      alto: 2,
      peso: 2.65,
      fuerzaExp: 2.6,
    },
    isComparable: true,
    caracteristicas: ["N35"],
  },
  {
    id: 30,
    label: "15x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 910,
      },
      prices_qtts: {
        "1": 910,
        "20": 860,
        "40": 760,
        "80": 660,
        "200": 620,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 15,
      alto: 2,
      peso: 2.65,
      fuerzaExp: 3.5,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N40",
    },
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo/up/MLAU2991085905",
    },
  },
  {
    id: 31,
    label: "15x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1600,
      },
      prices_qtts: {
        "1": 1600,
        "10": 1500,
        "25": 1350,
        "50": 1170,
        "120": 1100,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 15,
      alto: 5,
      peso: 6.6,
      fuerzaExp: 5.7,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N52",
    },
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo/up/MLAU3009553563",
    },
  },
  {
    id: 32,
    label: "20x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1270,
      },
      prices_qtts: {
        "1": 1270,
        "20": 1200,
        "40": 1060,
        "80": 920,
        "200": 870,
      },
      update: "13/3/2025",
    },
    measures: {
      largo: 20,
      alto: 2,
      peso: 4.8,
      fuerzaExp: 4.7,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo/up/MLAU2991086403",
    },
  },
  {
    id: 33,
    label: "20x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 2500,
      },
      prices_qtts: {
        "1": 2500,
        "10": 2350,
        "25": 2150,
        "50": 1900,
        "120": 1800,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 20,
      alto: 5,
      peso: 12,
      fuerzaExp: 7,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo/up/MLAU3014771058",
    },
  },
  {
    hidden: true,
    id: 34,
    label: "25x2mm N35",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1750,
      },
      prices_qtts: {
        "1": 1750,
        "25": 1650,
        "50": 1480,
        "100": 1330,
        "250": 1250,
        "500": 1180,
      },
      update: "21/4",
    },
    measures: {
      largo: 25,
      alto: 2,
      peso: 5.76,
      fuerzaExp: 1.8,
    },
    isComparable: true,
    caracteristicas: ["N35"],
  },
  {
    id: 35,
    label: "25x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 2200,
      },
      prices_qtts: {
        "1": 2200,
        "10": 2100,
        "25": 1900,
        "50": 1700,
        "120": 1600,
      },
      update: "20/8/2025",
    },
    measures: {
      largo: 25,
      alto: 2,
      peso: 5.76,
      fuerzaExp: 4.6,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo/up/MLAU2991085901",
    },
  },
  {
    id: 36,
    label: "25x2.5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1750,
      },
      prices_qtts: {
        "1": 1750,
        "10": 1650,
        "25": 1470,
        "50": 1270,
        "120": 1200,
      },
      update: "17/5/2025",
    },
    measures: {
      largo: 25,
      alto: 2.5,
      peso: 9.3,
      fuerzaExp: 4.5,
    },
    isComparable: true,
  },
  {
    id: 37,
    label: "25x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 3050,
      },
      prices_qtts: {
        "1": 3050,
        "10": 2900,
        "25": 2700,
        "50": 2450,
        "120": 2300,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 25,
      alto: 5,
      peso: 18,
      fuerzaExp: 7.3,
    },
    isComparable: true,
  },
  {
    id: 38,
    label: "30x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "discount",
      prices: {
        base: 2500,
        discount: 2000,
      },
      discountsPercentages: {
        discount: 0.2,
      },
      prices_qtts: {
        "1": 2500,
        "10": 2350,
        "25": 2150,
        "50": 1900,
        "120": 1800,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 30,
      alto: 3,
      peso: 17.5,
      fuerzaExp: 5.3,
    },
    isComparable: true,
  },
  {
    id: 39,
    label: "30x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 4850,
      },
      prices_qtts: {
        "1": 4850,
        "10": 4650,
        "25": 4500,
        "50": 4350,
        "120": 4150,
      },
      update: "17/1/2025",
    },
    measures: {
      largo: 30,
      alto: 5,
      peso: 26.5,
    },
    isComparable: true,
  },
  {
    id: 40,
    label: "35x4mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "discount",
      prices: {
        base: 5050,
        discount: 4500,
      },
      discountsPercentages: {
        discount: 0.11,
      },
      prices_qtts: {
        "1": 5050,
        "10": 4850,
        "25": 4700,
        "50": 4500,
        "120": 4350,
      },
      update: "17/1/2025",
    },
    measures: {
      largo: 35,
      alto: 4,
      peso: 30,
    },
    isComparable: true,
  },
  {
    noStock: true,
    id: 41,
    label: "35x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 5450,
      },
      prices_qtts: {
        "1": 5450,
        "10": 5250,
        "25": 5050,
        "50": 4850,
        "120": 4700,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 35,
      alto: 5,
      peso: 36,
    },
    isComparable: true,
  },
  {
    id: 42,
    label: "37x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "discount",
      prices: {
        base: 5900,
        discount: 4800,
      },
      discountsPercentages: {
        discount: 0.13,
      },
      prices_qtts: {
        "1": 5900,
        "5": 5700,
        "15": 5450,
        "30": 5250,
        "80": 5000,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 37,
      alto: 5,
      peso: 40.3,
    },
    isComparable: true,
  },
  {
    id: 43,
    label: "38x8mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "discount",
      prices: {
        base: 9050,
        discount: 8000,
      },
      discountsPercentages: {
        discount: 0.12,
      },
      prices_qtts: {
        "1": 9050,
        "5": 8750,
        "15": 8400,
        "30": 8050,
        "80": 7700,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 38,
      alto: 8,
      peso: 65,
      fuerzaExp: 18,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N45",
    },
  },
  {
    noStock: true,
    id: 44,
    label: "40x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 6100,
      },
      prices_qtts: {
        "1": 6100,
        "5": 5900,
        "15": 5650,
        "30": 5400,
        "80": 5200,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 40,
      alto: 5,
      peso: 46.5,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N48",
    },
  },
  {
    id: 45,
    label: "54x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 6550,
      },
      prices_qtts: {
        "1": 6550,
        "5": 6300,
        "15": 6050,
        "30": 5800,
        "80": 5550,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 54,
      alto: 3,
      peso: 74,
    },
    isComparable: true,
  },
  {
    noStock: true,
    id: 46,
    label: "10x5x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 385,
      },
      prices_qtts: {
        "1": 385,
        "25": 360,
        "50": 320,
        "100": 280,
        "500": 260,
        "1000": 245,
      },
    },
    measures: {
      largo: 10,
      ancho: 5,
      alto: 2,
      peso: 0.9,
    },
    isComparable: true,
  },
  {
    noStock: true,
    id: 47,
    label: "10x8x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 510,
      },
      prices_qtts: {
        "1": 510,
        "25": 480,
        "50": 425,
        "100": 370,
        "500": 350,
        "1000": 325,
      },
      update: "13/3/2025",
    },
    measures: {
      largo: 10,
      ancho: 8,
      alto: 3,
      peso: 1.8,
      fuerzaExp: 2,
    },
    isComparable: true,
  },
  {
    id: 48,
    label: "10x10x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["cuadrado", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 410,
      },
      prices_qtts: {
        "1": 410,
        "25": 390,
        "50": 345,
        "100": 300,
        "500": 280,
        "1000": 265,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 10,
      ancho: 10,
      alto: 2,
      peso: 2,
      fuerzaExp: 2,
    },
    isComparable: true,
  },
  {
    id: 49,
    label: "14.5x7x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 600,
      },
      prices_qtts: {
        "1": 600,
        "25": 570,
        "50": 500,
        "100": 435,
        "250": 410,
        "500": 385,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 14.5,
      ancho: 7,
      alto: 2,
      peso: 1.6,
      fuerzaExp: 2,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-cuadrado/up/MLAU2996494804",
    },
  },
  {
    noStock: true,
    id: 50,
    label: "15x10x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1450,
      },
      prices_qtts: {
        "1": 1450,
        "10": 1370,
        "25": 1210,
        "50": 1050,
        "120": 990,
      },
      update: "25/3/2025",
    },
    measures: {
      largo: 15,
      ancho: 10,
      alto: 5,
      peso: 5.6,
      fuerzaExp: 4,
    },
    isComparable: true,
  },
  {
    noStock: true,
    id: 51,
    label: "20x10x10mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "bloque"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 3050,
      },
      prices_qtts: {
        "1": 3050,
        "10": 2900,
        "25": 2700,
        "50": 2450,
        "120": 2300,
      },
      update: "17/1/2025",
    },
    measures: {
      largo: 20,
      ancho: 10,
      alto: 10,
      peso: 15,
      fuerzaExp: 6.7,
    },
    isComparable: true,
  },
  {
    id: 52,
    label: "25x10x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1250,
      },
      prices_qtts: {
        "1": 1250,
        "20": 1180,
        "40": 1050,
        "80": 910,
        "200": 860,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 25,
      ancho: 10,
      alto: 2,
      peso: 4,
      fuerzaExp: 3.8,
    },
    isComparable: true,
  },
  {
    id: 53,
    label: "28x20x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 2500,
      },
      prices_qtts: {
        "1": 2500,
        "10": 2350,
        "25": 2150,
        "50": 1900,
        "120": 1800,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 28,
      ancho: 20,
      alto: 3,
      peso: 12.6,
      fuerzaExp: 4.8,
    },
    isComparable: true,
  },
  {
    noStock: true,
    id: 54,
    label: "30x10x10mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 3700,
      },
      prices_qtts: {
        "1": 3700,
        "10": 3500,
        "25": 3250,
        "50": 2950,
        "120": 2800,
      },
      update: "17/1/2025",
    },
    measures: {
      largo: 30,
      ancho: 10,
      alto: 10,
      peso: 22.5,
    },
    isComparable: true,
  },
  {
    id: 55,
    label: "30x20x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 4650,
      },
      prices_qtts: {
        "1": 4650,
        "10": 4500,
        "25": 4350,
        "50": 4200,
        "120": 4000,
      },
      update: "17/1/2025",
    },
    measures: {
      largo: 30,
      ancho: 20,
      alto: 5,
      peso: 24,
      fuerzaExp: 8,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-cuadrado/up/MLAU2991310517",
    },
  },
  {
    id: 56,
    label: "40x10x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 4350,
      },
      prices_qtts: {
        "1": 4350,
        "10": 4100,
        "25": 3950,
        "50": 3700,
        "120": 3500,
      },
      update: "17/1/2025",
    },
    measures: {
      largo: 40,
      ancho: 10,
      alto: 5,
      peso: 15.5,
      fuerzaExp: 5.9,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-cuadrado/up/MLAU3014646394",
    },
  },
  {
    id: 57,
    label: "40x20x5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 8950,
      },
      prices_qtts: {
        "1": 8950,
        "5": 8600,
        "15": 8250,
        "30": 7900,
        "80": 7600,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 40,
      ancho: 20,
      alto: 5,
      peso: 31.5,
    },
    isComparable: true,
  },
  {
    id: 58,
    label: "40x25x10mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "discount",
      prices: {
        base: 16100,
        discount: 14500,
      },
      discountsPercentages: {
        discount: 0.1,
      },
      prices_qtts: {
        "1": 16100,
        "5": 15600,
        "15": 15100,
        "30": 14600,
        "80": 14100,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 40,
      ancho: 25,
      alto: 10,
      peso: 84,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-cuadrado/up/MLAU3014645500",
    },
  },
  {
    id: 59,
    label: "50x10x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 3800,
      },
      prices_qtts: {
        "1": 3800,
        "10": 3550,
        "25": 3350,
        "50": 3050,
        "120": 2850,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 50,
      ancho: 10,
      alto: 3,
      peso: 12,
      fuerzaExp: 3.9,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-cuadrado/up/MLAU2991312469",
    },
  },
  {
    id: 60,
    label: "50x20x10mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "discount",
      prices: {
        base: 17200,
        discount: 15500,
      },
      discountsPercentages: {
        discount: 0.1,
      },
      prices_qtts: {
        "1": 17200,
        "5": 16700,
        "15": 16200,
        "30": 15700,
        "80": 15200,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 50,
      ancho: 20,
      alto: 10,
      peso: 75,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-cuadrado/up/MLAU3013557579",
    },
  },
  {
    noStock: true,
    id: 61,
    label: "50x24x10mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 18700,
      },
      prices_qtts: {
        "1": 18700,
        "5": 18200,
        "15": 17700,
        "30": 17200,
        "80": 16700,
      },
      update: "17/1/2025",
    },
    measures: {
      largo: 50,
      ancho: 24,
      alto: 10,
      peso: 85,
    },
    isComparable: true,
  },
  {
    id: 62,
    label: "8x3mm 6a3.5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "fresado"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 455,
      },
      prices_qtts: {
        "1": 455,
        "25": 430,
        "50": 380,
        "100": 330,
        "500": 310,
        "1000": 295,
      },
      update: "17/1/2025",
    },
    measures: {
      largo: 8,
      alto: 3,
      diametroSup: 6,
      diametroInf: 3.5,
      peso: 0.7,
      fuerzaExp: 0.4,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo-fresado-x10u--arandela/up/MLAU2995880070",
      MS: "https://imanestucuman.mercadoshops.com.ar/iman-neodimio-redondo-fresado-x10u--arandela/up/MLAU2995880070",
    },
    tags: ["arandela"],
  },
  {
    id: 63,
    label: "12x3mm 6a3.5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "fresado"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 710,
      },
      prices_qtts: {
        "1": 710,
        "25": 670,
        "50": 590,
        "100": 510,
        "250": 485,
        "500": 455,
      },
      update: "17/1/2025",
    },
    measures: {
      largo: 12,
      alto: 3,
      diametroSup: 6,
      diametroInf: 3.5,
      peso: 2.3,
      fuerzaExp: 2.3,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo-fresado-x10u--arandela/up/MLAU2990693417",
      MS: "https://imanestucuman.mercadoshops.com.ar/iman-neodimio-redondo-fresado-x10u--arandela/up/MLAU2990693417",
    },
    tags: ["arandela"],
  },
  {
    id: 64,
    label: "15x3mm 7a3.5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "fresado"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1000,
      },
      prices_qtts: {
        "1": 1000,
        "20": 950,
        "40": 840,
        "80": 730,
        "200": 680,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 15,
      alto: 3,
      diametroSup: 7,
      diametroInf: 3.5,
      peso: 3.7,
      fuerzaExp: 4.5,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo-fresado-x10u--arandela/up/MLAU2995893094",
      MS: "https://imanestucuman.mercadoshops.com.ar/iman-neodimio-redondo-fresado-x10u--arandela/up/MLAU2995893094",
    },
    tags: ["arandela"],
  },
  {
    id: 65,
    label: "20x4mm 11a4.5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "fresado"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1800,
      },
      prices_qtts: {
        "1": 1800,
        "10": 1700,
        "25": 1550,
        "50": 1390,
        "120": 1310,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 20,
      alto: 4,
      diametroSup: 11,
      diametroInf: 4.5,
      peso: 9.4,
      fuerzaExp: 5,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-redondo-fresado-x10u--arandela/up/MLAU2990699711",
      MS: "https://imanestucuman.mercadoshops.com.ar/iman-neodimio-redondo-fresado-x10u--arandela/up/MLAU2990699711",
    },
    tags: ["arandela"],
  },
  {
    id: 66,
    label: "20x10x5mm 8a4mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "fresado"],
    price_data: {
      usePrice: "discount",
      prices: {
        base: 3700,
        discount: 3000,
      },
      discountsPercentages: {
        discount: 0.2,
      },
      prices_qtts: {
        "1": 3700,
        "10": 3500,
        "25": 3250,
        "50": 2950,
        "120": 2800,
      },
      update: "17/1/2025",
    },
    measures: {
      largo: 20,
      ancho: 10,
      alto: 5,
      diametroSup: 8,
      diametroInf: 4,
      peso: 12.5,
      fuerzaExp: 4.3,
    },
    isComparable: true,
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-cuadrado-fresado/up/MLAU2991651617",
      MS: "https://imanestucuman.mercadoshops.com.ar/iman-neodimio-cuadrado-fresado/up/MLAU2991651617",
    },
  },
  {
    hidden: true,
    noStock: true,
    id: 67,
    label: "20mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "arrastre"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 12000,
      },
      update: "30/7/25",
    },
    measures: {
      largo: 20,
      alto: 6,
      altoTotal: 26,
      fuerza: 7,
      peso: 23,
    },
    isComparable: true,
    tags: ["pesca"],
  },
  {
    noStock: true,
    id: 68,
    label: "25mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "arrastre"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 12250,
      },
      update: "12/8/25",
    },
    measures: {
      largo: 25,
      alto: 7,
      altoTotal: 31,
      fuerza: 22,
      peso: 42,
    },
    isComparable: true,
    tags: ["pesca"],
  },
  {
    id: 69,
    label: "32mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "arrastre"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 16500,
      },
      update: "12/8/25",
    },
    measures: {
      largo: 32,
      alto: 7,
      altoTotal: 31,
      fuerza: 28,
      peso: 70,
    },
    isComparable: true,
    tags: ["pesca"],
  },
  {
    noStock: true,
    id: 70,
    label: "36mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "arrastre"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 20000,
      },
      update: "12/8/25",
    },
    measures: {
      largo: 36,
      alto: 7.3,
      altoTotal: 38,
      fuerza: 31,
      peso: 85,
    },
    isComparable: true,
    tags: ["pesca"],
  },
  {
    id: 71,
    label: "42mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "arrastre"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 22000,
      },
      update: "12/8/25",
    },
    measures: {
      largo: 42,
      alto: 7.5,
      altoTotal: 38,
      fuerza: 40,
      peso: 118,
    },
    isComparable: true,
    tags: ["pesca"],
  },
  {
    id: 72,
    label: "48mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "arrastre"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 25000,
      },
      update: "5/9/25",
    },
    measures: {
      largo: 48,
      alto: 11.5,
      altoTotal: 49,
      fuerza: 88,
      peso: 249,
    },
    isComparable: true,
    tags: ["pesca"],
  },
  {
    id: 73,
    label: "75mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "arrastre"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 34000,
      },
      update: "12/8/25",
    },
    measures: {
      largo: 75,
      alto: 18,
      altoTotal: 62,
      fuerza: 240,
      peso: 670,
    },
    isComparable: true,
    tags: ["pesca"],
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-neodimio-pescaarrastre/up/MLAU3011716256",
    },
  },
  {
    hidden: true,
    noStock: true,
    id: 74,
    label: "Bornera Botón 2 Vías",
    categorie: ["electricidad"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 180,
      },
      prices_qtts: {
        "1": 180,
        "10": 150,
      },
    },
    caracteristicas: ["reutilizable"],
    especificaciones: {
      medidas: "20x17x13mm",
      cables: "0.5-2.5mm",
      amperaje: "10A",
      materiales: "PVC",
      peso: "1.75g",
    },
    description:
      "Se recomienda su uso para conexiones de baja tensión, como lámparas",
  },
  {
    id: 75,
    label: "Bornera Clip 2 Vías",
    categorie: ["electricidad"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1500,
      },
      prices_qtts: {
        "1": 1500,
        "3": 1250,
      },
    },
    caracteristicas: ["reutilizable"],
    especificaciones: {
      medidas: "40x25x15mm",
      cables: "0.5-2.5mm",
      amperaje: "32A",
      voltaje: "450v",
      materiales: "ABS",
      peso: "8g",
    },
    links: {
      ML: "https://articulo.mercadolibre.com.ar/MLA-1877354416-borneraterminalconectorempalme-clip-2-vias-x3u-_JM#origin%3Dshare%26sid%3Dshare",
      MS: "https://imanestucuman.mercadoshops.com.ar/MLA-1877354416-borneraterminalconectorempalme-clip-2-vias-x3u-_JM?searchVariation=181314142862",
    },
  },
  {
    id: 76,
    label: "Bornera Clip 3 Vías",
    categorie: ["electricidad"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 2000,
      },
      prices_qtts: {
        "1": 2000,
        "3": 1850,
        "5": 1700,
      },
    },
    caracteristicas: ["reutilizable"],
    especificaciones: {
      medidas: "41x31x15mm",
      cables: "0.5-2.5mm",
      amperaje: "32A",
      voltaje: "450v",
      materiales: "ABS",
      peso: "11.4g",
    },
    links: {
      ML: "https://articulo.mercadolibre.com.ar/MLA-1877316430-borneraterminalconectorempalme-clip-3-vias-x3u-_JM#origin%3Dshare%26sid%3Dshare",
      MS: "https://imanestucuman.mercadoshops.com.ar/MLA-1877316430-borneraterminalconectorempalme-clip-3-vias-x3u-_JM?searchVariation=181314187502",
    },
  },
  {
    id: 77,
    label: "Empalme Clip 2 Bocas",
    categorie: ["electricidad"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 580,
      },
      prices_qtts: {
        "1": 580,
        "10": 500,
        "20": 450,
      },
    },
    caracteristicas: ["reutilizable"],
    especificaciones: {
      medidas: "20x12x14mm",
      cables: "0.2-2.5mm",
      amperaje: "32A",
      voltaje: "250v",
      materiales: "ABS",
    },
    links: {
      ML: "https://articulo.mercadolibre.com.ar/MLA-1877351970-borneraterminalconectorempalme-clip-2-cables-x5u-_JM#origin%3Dshare%26sid%3Dshare",
      MS: "https://imanestucuman.mercadoshops.com.ar/MLA-1877351970-borneraterminalconectorempalme-clip-2-cables-x5u-_JM?searchVariation=181314138382",
    },
  },
  {
    id: 78,
    label: "Empalme Clip 3 Bocas",
    categorie: ["electricidad"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 800,
      },
      prices_qtts: {
        "1": 800,
        "10": 700,
      },
    },
    caracteristicas: ["reutilizable"],
    especificaciones: {
      medidas: "20x16x14mm",
      cables: "0.2-2.5mm",
      amperaje: "32A",
      voltaje: "250v",
      materiales: "ABS",
    },
    links: {
      ML: "https://articulo.mercadolibre.com.ar/MLA-1877326576-borneraterminalconectorempalme-clip-3-cables-x5u-_JM#origin%3Dshare%26sid%3Dshare",
      MS: "https://imanestucuman.mercadoshops.com.ar/MLA-1877326576-borneraterminalconectorempalme-clip-3-cables-x5u-_JM?searchVariation=184148246937",
    },
  },
  {
    id: 79,
    label: "Empalme Clip 5 Bocas",
    categorie: ["electricidad"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1200,
      },
      prices_qtts: {
        "1": 1200,
        "10": 1000,
      },
    },
    caracteristicas: ["reutilizable"],
    especificaciones: {
      medidas: "20x26x14mm",
      cables: "0.2-2.5mm",
      amperaje: "32A",
      voltaje: "250v",
      materiales: "ABS",
    },
    links: {
      ML: "https://articulo.mercadolibre.com.ar/MLA-1877327498-borneraterminalconectorempalme-clip-5-cables-x5u-_JM#origin%3Dshare%26sid%3Dshare",
      MS: "https://imanestucuman.mercadoshops.com.ar/MLA-1877327498-borneraterminalconectorempalme-clip-5-cables-x5u-_JM?searchVariation=184148250357",
    },
  },
  {
    id: 80,
    label: "Empalme Rápido Derivador",
    categorie: ["electricidad"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 600,
      },
      prices_qtts: {
        "1": 600,
        "10": 500,
      },
    },
    caracteristicas: ["exterior"],
    especificaciones: {
      medidas: "27x24x16mm",
      cables: "1-2.5mm",
      amperaje: "1.5-17.5A/1-13.5A",
      materiales: "PVC",
      peso: "3g",
    },
    description: "Deriva un cable de 1.5-2.5 a uno de 1-1.5",
    links: {
      ML: "https://articulo.mercadolibre.com.ar/MLA-1877283648-empalme-rapido-exterior-1a2-cables-x5u-_JM#origin%3Dshare%26sid%3Dshare",
      MS: "https://imanestucuman.mercadoshops.com.ar/MLA-1877283648-empalme-rapido-exterior-1a2-cables-x5u-_JM?utm_source=mercadoshops",
    },
  },
  {
    id: 81,
    label: "Empalme Rápido 3 Bocas",
    categorie: ["electricidad"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 750,
      },
      prices_qtts: {
        "1": 750,
        "10": 700,
        "20": 600,
        "50": 575,
      },
    },
    especificaciones: {
      marca: "Hellermann Tyton",
      medidas: "16.5x16.5x7.7mm",
      cables: "1-2.5mm",
      amperaje: "20A",
      voltaje: "450V",
      materiales: "Policarbonato",
      modelo: "Helacon Plus",
    },
    description:
      "Con solo quitar el recubrimiento de la punta puede empalmar 3 cables eléctricos en segundos con su traba de tipo clip. Posee punto de testeo. No reutilizable.",
    links: {
      ML: "https://articulo.mercadolibre.com.ar/MLA-1877317474-empalme-rapido-3-cables-x5u-_JM#origin%3Dshare%26sid%3Dshare",
      MS: "https://imanestucuman.mercadoshops.com.ar/MLA-1877317474-empalme-rapido-3-cables-x5u-_JM?searchVariation=181314194258",
    },
  },
  {
    id: 82,
    label: "Tira 9x2mm",
    categorie: ["imanes", "flexibles"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1800,
      },
      prices_qtts: {
        "1": 1800,
        "5": 1600,
        "10": 1450,
        "25": 1300,
        "50": 1120,
        "100": 970,
      },
      update: "1/8/25",
      salesUnit: "m",
    },
    measures: {
      largo: 9,
      alto: 2,
    },
    especificaciones: {
      fuerza: "30g/cm",
    },
    description:
      "Imantado de una cara. Usado frecuentemente para hacer mosquiteros y manualidades",
    links: {
      ML: "https://articulo.mercadolibre.com.ar/MLA-1985406268-iman-tira-flexible-9x2mm-x10m-_JM#origin%3Dshare%26sid%3Dshare",
      MS: "https://imanestucuman.mercadoshops.com.ar/MLA-1985406268-iman-tira-flexible-9x2mm-x10m-_JM#item_id=MLA1985406268",
    },
  },
  {
    id: 83,
    label: "Tira 13x1,7mm",
    categorie: ["imanes", "flexibles"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 2000,
      },
      prices_qtts: {
        "1": 2000,
        "5": 1800,
        "10": 1600,
        "25": 1400,
        "50": 1250,
        "100": 1130,
      },
      update: "1/8/25",
      salesUnit: "m",
    },
    measures: {
      largo: 13,
      alto: 1.7,
    },
    especificaciones: {
      fuerza: "32g/cm",
    },
    description:
      "Imantado de una cara. Usado frecuentemente para hacer mosquiteros y manualidades",
    links: {
      ML: "https://articulo.mercadolibre.com.ar/MLA-1985431476-iman-tira-flexible-13x17mm-x10m-_JM#origin%3Dshare%26sid%3Dshare",
      MS: "https://imanestucuman.mercadoshops.com.ar/MLA-1985431476-iman-tira-flexible-13x17mm-x10m-_JM#item_id=MLA1985431476",
    },
  },
  {
    id: 84,
    label: "Kluster",
    categorie: ["imanes", "otrosImanes"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 12000,
      },
      update: "5/9/25",
    },
    description:
      "Juego de 20 piedras ovaladas de hematita magnetizadas y pulidas de 35mm de largo y 13mm de diámetro central + cuerda de polipropileno",
    links: {
      ML: "https://www.mercadolibre.com.ar/juego-imanes-ovalados-x20piezaskluster/up/MLAU2480455379",
      MS: "https://imanestucuman.mercadoshops.com.ar/juego-imanes-ovalados-x20piezaskluster/up/MLAU2480455379",
    },
    tags: ["juguetes", "antiestres"],
  },
  {
    hidden: true,
    id: 85,
    label: "Neocube",
    categorie: ["imanes", "otrosImanes"],
    forma: ["esfera"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 18500,
      },
      update: "1/7/25",
    },
    description:
      "216 imanes esféricos de 5mm de diámetro. Multicolor(6 distintos)",
    tags: ["juguetes"],
  },
  {
    noStock: true,
    id: 86,
    label: "Neocube Dorado",
    categorie: ["imanes", "otrosImanes"],
    forma: ["esfera"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 18500,
      },
    },
    measures: {
      largo: 5,
      alto: 5,
      ancho: 5,
    },
    isComparable: true,
    description: "216 imanes esféricos de 5mm de diámetro de color dorado",
    tags: ["juguetes"],
  },
  {
    id: 87,
    label: "60x8x6mm",
    categorie: ["imanes", "ferrita"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 4600,
      },
      update: "29/8/2025",
    },
    measures: {
      largo: 60,
      ancho: 8,
      alto: 6,
      peso: 14.75,
      gauss: 4000,
    },
    isComparable: true,
    description:
      "Frecuentemente usado para soportar puertas de hornos que no cierran bien",
    tags: ["ceramico"],
  },
  {
    hidden: true,
    id: 88,
    label: "25x14x5mm",
    categorie: ["imanes", "ferrita"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 2100,
      },
    },
    measures: {
      largo: 25,
      ancho: 14,
      alto: 5,
    },
    isComparable: true,
    tags: ["ceramico"],
  },
  {
    id: 89,
    label: "Lámina 03/31A",
    categorie: ["imanes", "flexibles"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 6400,
      },
      prices_qtts: {
        "1": 6400,
        "5": 6000,
        "0.2": 7400,
        "0.5": 6900,
      },
      salesUnit: "m",
      salesDecimal: [0.2, 0.5],
      update: "15/9/2025",
    },
    measures: {
      largo: 310,
      alto: 0.3,
    },
    especificaciones: {
      fuerza: "20g/cm",
      peso: "416g/m",
    },
    caracteristicas: ["autoadhesiva"],
    description:
      "Usada generalmente en souvenirs, manualidades, calendarios, imanes publicitarios, etc",
    links: {
      ML: "https://www.mercadolibre.com.ar/iman-plancha-flexible-adhesivo-31cmx03mmx1mm/up/MLAU3114462818",
      MS: "https://imanestucuman.mercadoshops.com.ar/iman-plancha-flexible-adhesivo-31cmx03mmx1mm/up/MLAU3114462818",
    },
    tags: ["plancha", "papel", "adhesivo"],
  },
  {
    id: 90,
    label: "Sales de polifosfato alemanas",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 25000,
      },
      salesUnit: "kg",
      update: "1/8/25",
    },
    caracteristicas: ["Calidad Alimentaria"],
    especificaciones: {
      modelo: "Alemana",
      diámetro: "20mm",
      rendimiento: "8-12meses en tanque de 1000L y 6-8 meses en boya(aprox.)",
    },
  },
  {
    id: 91,
    label: "Sales de polifosfato italianas",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 23000,
      },
      salesUnit: "kg",
      update: "1/8/25",
    },
    caracteristicas: ["Calidad Alimentaria"],
    especificaciones: {
      modelo: "Italiana",
    },
  },
  {
    id: 92,
    label: "Sales de polifosfato alemanas(Outlet)",
    categorie: ["otros"],
    price_data: {
      usePrice: "discount",
      prices: {
        base: 25000,
        discount: 23000,
      },
      discountsPercentages: {
        discount: 0.04,
      },
      salesUnit: "kg",
      update: "1/8/25",
    },
    especificaciones: {
      modelo: "Alemana",
      diámetro: "20mm",
      rendimiento: "8-12meses en tanque de 1000L y 6-8 meses en boya(aprox.)",
    },
    description:
      "SE MOJARON UN POCO DURANTE UNA TORMENTA, IGUALMENTE FUNCIONAN",
  },
  {
    id: 93,
    label: "9.56x3.17mm 6a3.5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "fresado"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 530,
      },
      prices_qtts: {
        "1": 530,
        "25": 500,
        "50": 440,
        "100": 380,
        "500": 360,
        "1000": 340,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 9.56,
      alto: 3.17,
      diametroSup: 6,
      diametroInf: 3.5,
      peso: 1.33,
      fuerzaExp: 1.7,
    },
    isComparable: true,
    tags: ["arandela"],
  },
  {
    id: 94,
    label: "Piedras magnéticas ovaladas",
    categorie: ["imanes", "otrosImanes"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 800,
      },
      prices_qtts: {
        "1": 800,
        "10": 700,
        "20": 600,
        "50": 500,
      },
      update: "5/9/25",
    },
    measures: {
      largo: 35,
      alto: 14,
    },
    description:
      "De hematita, magnetizadas y pulidas de 35mm de largo y 14mm de diámetro central. Son suaves y al golpearse entre si producen vibraciones. Usados en tratamientos antiestrés",
    links: {
      ML: "https://articulo.mercadolibre.com.ar/MLA-1989274886-pack-imanes-ovalados-x20-_JM#origin%3Dshare%26sid%3Dshare",
      MS: "https://imanestucuman.mercadoshops.com.ar/MLA-1989274886-pack-imanes-ovalados-x20-_JM#item_id=MLA1989274886",
    },
    tags: ["juguetes", "antiestres"],
  },
  {
    noStock: true,
    id: 95,
    label: "16x3mm",
    categorie: ["imanes", "ferrita"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 140,
      },
      prices_qtts: {
        "1": 140,
        "25": 125,
        "50": 110,
        "100": 100,
      },
      update: "13/8/25",
    },
    measures: {
      largo: 16,
      alto: 3,
      peso: 2.7,
      fuerzaExp: 0.23,
    },
    isComparable: true,
    description:
      "Usados frecuentemente en manualidades, artesanias, heladeras, etc",
    tags: ["ceramico"],
  },
  {
    noStock: true,
    id: 96,
    label: "7x1.5mm N35",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 135,
      },
      prices_qtts: {
        "1": 135,
        "25": 130,
        "50": 115,
        "100": 100,
        "500": 95,
        "1000": 90,
      },
      update: "23/5",
    },
    measures: {
      largo: 7,
      alto: 1.5,
      peso: 0.4,
      fuerzaExp: 0.3,
    },
    isComparable: true,
    caracteristicas: ["N35"],
  },
  {
    id: 97,
    label: "9x1.5mm N35",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 155,
      },
      prices_qtts: {
        "1": 155,
        "25": 145,
        "50": 130,
        "100": 110,
        "500": 105,
        "1000": 100,
      },
      update: "23/5",
    },
    measures: {
      largo: 9,
      alto: 1.5,
      peso: 0.7,
      fuerzaExp: 0.6,
    },
    isComparable: true,
    caracteristicas: ["N35"],
  },
  {
    id: 98,
    label: "6x4mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "boton"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 300,
      },
      prices_qtts: {
        "1": 300,
        "25": 285,
        "50": 250,
        "100": 215,
        "500": 205,
        "1000": 190,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 6,
      alto: 4,
      peso: 0.9,
      fuerzaExp: 0.84,
    },
    isComparable: true,
  },
  {
    id: 99,
    label: "Pegamento Poxipol 21g/14ml",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 5500,
      },
      update: "27/6/25",
    },
    caracteristicas: [
      "Gran resistencia",
      "Gran durabilidad",
      "Resistente al agua",
    ],
    especificaciones: {
      colo: "Gris metálico",
      resistencia: "1000kg",
      endurecimiento: "10min",
      pega: "metal, cemento, loza, madera, mármol, vidrio, cerámica y porcelana",
    },
    description:
      "Adhesivo epoxi o soldadura plástica de 2 componentes que se mezclan y aplican",
  },
  {
    id: 100,
    label: "Pegamento Éccole 3g",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 2500,
      },
      update: "27/6/25",
    },
    caracteristicas: ["Sin olor", "No inflamable"],
    description:
      "Adhesivo de cianoacrilato.\n Pega en 60 segundos, pero su resistencia final se logra luego de 3 horas de secado.\n No adhiere sobre polietileno, polipropileno, teflón ni superficies siliconadas",
  },
  {
    id: 103,
    label: "Para Portón Automático",
    categorie: ["imanes", "otrosImanes"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 6500,
      },
      prices_qtts: {
        "1": 6500,
        "2": 6000,
        "4": 5500,
      },
      update: "21/7/25",
    },
    measures: {
      alto: 10,
      altoTotal: 28,
      largo: 50,
      ancho: 25,
    },
    caracteristicas: ["con portante"],
    description:
      "Compatible con todos los equipos que trabajan con imanes como final de carrera",
    tags: ["porton", "automatico"],
  },
  {
    id: 104,
    label: "Masa magnética p/soldar",
    categorie: ["imanes", "otrosImanes"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 8500,
      },
      update: "30/7/25",
    },
    measures: {
      largo: 51,
      alto: 25,
      fuerza: 10,
    },
    tags: ["ferrita", "metal"],
  },
  {
    id: 105,
    label: "Linterna led llavero magnético",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 3200,
      },
      update: "30/7/25",
    },
    measures: {
      largo: 45,
      alto: 61,
      peso: 40,
    },
    caracteristicas: ["recargable", "incluye USB"],
    especificaciones: {
      potencia: "800 lúmenes",
      luz: "blanca",
      duración: "6h",
      batería: "litio",
    },
    description:
      "Con sus 4 modos de iluminación es idea para diversas actividades, desde camping y exploración hasta reparaciones en el hogar y cortes de luz. Tiene resistencia al agua y al polvo; y un imán que permite fijarlo en superficies metálicas",
    tags: ["auto", "herramienta", "herramientas"],
  },
  {
    id: 106,
    label: "6x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 175,
      },
      prices_qtts: {
        "1": 175,
        "25": 165,
        "50": 145,
        "100": 125,
        "500": 120,
        "1000": 110,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 6,
      alto: 2,
      peso: 0.42,
      fuerzaExp: 0.83,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N40",
    },
  },
  {
    id: 107,
    label: "10x10x10mm",
    categorie: ["imanes", "neodimio"],
    forma: ["cuadrado", "cubico"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 2050,
      },
      prices_qtts: {
        "1": 2050,
        "10": 1950,
        "25": 1750,
        "50": 1550,
        "120": 1480,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 10,
      alto: 10,
      ancho: 10,
      peso: 7.5,
      fuerzaExp: 1.8,
    },
    isComparable: true,
  },
  {
    id: 108,
    label: "50x20mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "arrastre"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 30000,
      },
      update: "8/8/25",
    },
    measures: {
      largo: 50,
      alto: 20,
      altoTotal: 60,
      fuerza: 50,
      fuerzaLevante: 20,
    },
    isComparable: true,
    caracteristicas: ["N46"],
    description: "El iman interior tiene 37x8mm",
    tags: ["pesca"],
  },
  {
    id: 109,
    label: "Linterna led trabajo",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 2000,
      },
      update: "8/8/25",
    },
    measures: {
      largo: 168,
      alto: 16,
      ancho: 28,
    },
    especificaciones: {
      luz: "blanca",
      batería: "x3 AAA",
    },
    description:
      "Cuenta con un imán que facilita colocarla en una posición cómoda. No incluye pilas",
    tags: [
      "auto",
      "magnetica",
      "iman",
      "camping",
      "herramienta",
      "herramientas",
    ],
  },
  {
    noStock: true,
    id: 110,
    label: "Magnetismo",
    categorie: ["imanes", "otrosImanes"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 14000,
      },
      update: "12/8/25",
    },
    measures: {
      largo: 275,
      ancho: 275,
      alto: 40,
    },
    caracteristicas: ["+14"],
    description:
      "Juego de mesa estratégico con imanes esféricos. Incluye 1 tablero y 20 imanes",
    tags: ["juguetes"],
  },
  {
    id: 111,
    label: "Tornillo 3mm",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 350,
      },
      update: "13/8/25",
    },
    measures: {
      largo: 3,
      alto: 25,
    },
    description: "Cabeza ranurada. Con tuerca y arandela",
  },
  {
    id: 112,
    label: "Tornillo 3,5mm",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 400,
      },
      update: "13/8/25",
    },
    measures: {
      largo: 3.5,
      alto: 25,
    },
    description: "Cabeza cruz. Con tuerca y arandela",
  },
  {
    id: 113,
    label: "Lámina 03/31V",
    categorie: ["imanes", "flexibles"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 5900,
      },
      prices_qtts: {
        "1": 5900,
        "5": 5500,
        "0.2": 6800,
        "0.5": 6300,
      },
      salesUnit: "m",
      salesDecimal: [0.2, 0.5],
      update: "15/9/2025",
    },
    measures: {
      largo: 310,
      alto: 0.3,
    },
    caracteristicas: ["virgen"],
    especificaciones: {
      fuerza: "20g/cm",
      peso: "363g/m",
    },
    description:
      "Usada generalmente en souvenirs, manualidades, calendarios, imanes publicitarios, etc",
    tags: ["plancha", "papel"],
  },
  {
    id: 114,
    label: "Lámina 03/61V",
    categorie: ["imanes", "flexibles"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 9300,
      },
      prices_qtts: {
        "1": 9300,
        "5": 8700,
        "0.2": 10700,
        "0.5": 10000,
      },
      salesUnit: "m",
      salesDecimal: [0.2, 0.5],
      update: "15/9/2025",
    },
    measures: {
      largo: 610,
      alto: 0.3,
    },
    caracteristicas: ["virgen"],
    especificaciones: {
      fuerza: "40g/cm",
      peso: "729g/m",
    },
    description:
      "Usada generalmente en souvenirs, manualidades, calendarios, imanes publicitarios, etc",
    tags: ["plancha", "papel"],
  },
  {
    noStock: true,
    id: 115,
    label: "Lámina 03/62A",
    categorie: ["imanes", "flexibles"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 12200,
      },
      prices_qtts: {
        "1": 12200,
        "5": 11500,
        "0.2": 14100,
        "0.5": 13200,
      },
      salesUnit: "m",
      salesDecimal: [0.2, 0.5],
      update: "15/9/2025",
    },
    measures: {
      largo: 620,
      alto: 0.3,
    },
    caracteristicas: ["autoadhesiva"],
    especificaciones: {
      fuerza: "40g/cm",
      peso: "832g/m",
    },
    description:
      "Usada generalmente en souvenirs, manualidades, calendarios, imanes publicitarios, etc",
    tags: ["plancha", "papel", "adhesivo"],
  },
  {
    id: 116,
    label: "15x4mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "boton"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1360,
      },
      prices_qtts: {
        "1": 1360,
        "20": 1290,
        "40": 1140,
        "80": 990,
        "200": 930,
      },
      update: "12/8/2025",
    },
    measures: {
      largo: 15,
      alto: 4,
      fuerzaExp: 2.35,
      peso: 5,
    },
    isComparable: true,
  },
  {
    id: 117,
    label: "20x10x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1550,
      },
      prices_qtts: {
        "1": 1550,
        "10": 1460,
        "25": 1290,
        "50": 1120,
        "120": 1050,
      },
      update: "28/8/2025",
    },
    measures: {
      largo: 20,
      ancho: 10,
      alto: 3,
      peso: 4.5,
      fuerzaExp: 4.5,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N45",
    },
  },
  {
    id: 118,
    label: "6x6x20mm",
    categorie: ["imanes", "neodimio"],
    forma: ["cuadrado", "bloque"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1450,
      },
      prices_qtts: {
        "1": 1450,
        "10": 1370,
        "25": 1210,
        "50": 1050,
        "120": 990,
      },
      update: "20/8/2025",
    },
    measures: {
      largo: 6,
      ancho: 6,
      alto: 20,
      fuerzaExp: 1.55,
      peso: 6,
    },
    isComparable: true,
  },
  {
    id: 119,
    label: "Bolígrafo Magnético",
    categorie: ["imanes", "otrosImanes"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 26000,
      },
      update: "13/9/2025",
    },
    especificaciones: {
      color: "negro",
      trazo: "0.5mm",
    },
    caracteristicas: ["Puntero Táctil"],
    description:
      "Incluye: estuche, 3 tubos de tinta, 1 clip, 13 tubos magnéticos, 2 esferas pequeñas, 8 esferas medianas, 2 esferas grandes, 2 tapas para bolígrafo, 1 tubo con punta para bolígrafo, 2 puntas para pantalla táctil. Los imanes son de neodimio",
    tags: ["juguetes", "antiestres"],
  },
  {
    id: 120,
    label: "Piedras magnéticas esféricas",
    categorie: ["imanes", "otrosImanes"],
    forma: ["esfera"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 800,
      },
      prices_qtts: {
        "1": 800,
        "10": 700,
        "20": 600,
        "50": 500,
      },
      update: "27/8/25",
    },
    measures: {
      diametro: 17,
    },
    description:
      "De hematita, magnetizadas y pulidas de 17mm de diámetro. Son suaves y al golpearse entre si producen vibraciones. Usados en tratamientos antiestrés",
    tags: ["juguetes", "antiestres"],
  },
  {
    id: 121,
    label: "Outlet: Piedras magnéticas",
    categorie: ["imanes", "otrosImanes"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 500,
      },
      update: "27/8/25",
    },
    description:
      "De hematita, magnetizadas y pulidas. Son suaves y al golpearse entre si producen vibraciones. Usados en tratamientos antiestrés. Esferas de 17mm y ovalados de 35x14mm",
    tags: ["juguetes", "antiestres"],
  },
  {
    id: 122,
    label: "12x3mm",
    categorie: ["imanes", "ferrita"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 90,
      },
      prices_qtts: {
        "1": 90,
        "25": 80,
        "50": 70,
        "100": 60,
      },
      update: "29/8/25",
    },
    measures: {
      largo: 12,
      alto: 3,
      peso: 1.63,
      fuerzaExp: 0.34,
    },
    isComparable: true,
    description:
      "Usados frecuentemente en manualidades, artesanias, heladeras, etc",
    tags: ["ceramico"],
  },
  {
    id: 123,
    label: "14x3mm",
    categorie: ["imanes", "ferrita"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 100,
      },
      prices_qtts: {
        "1": 100,
        "25": 90,
        "50": 80,
        "100": 65,
      },
      update: "29/8/25",
    },
    measures: {
      largo: 14,
      alto: 3,
      peso: 2,
      fuerzaExp: 0.37,
    },
    isComparable: true,
    description:
      "Usados frecuentemente en manualidades, artesanias, heladeras, etc",
    tags: ["ceramico"],
  },
  {
    id: 124,
    label: "20x3mm",
    categorie: ["imanes", "ferrita"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 165,
      },
      prices_qtts: {
        "1": 165,
        "25": 145,
        "50": 125,
        "100": 105,
      },
      update: "29/8/25",
    },
    measures: {
      largo: 20,
      alto: 3,
      fuerzaExp: 0.54,
    },
    isComparable: true,
    description:
      "Usados frecuentemente en manualidades, artesanias, heladeras, etc",
    tags: ["ceramico"],
  },
  {
    id: 125,
    label: "Bolsa Ecommerce 15x20cm",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 70,
      },
      prices_qtts: {
        "1": 70,
        "25": 55,
        "50": 45,
      },
      update: "29/8/25",
    },
    measures: {
      ancho: 15,
      alto: 25,
    },
    caracteristicas: ["Con adhesivo"],
    especificaciones: {
      color: "negro",
      grosor: "60 micrones",
    },
    description: "Solapa de 5cm",
    tags: ["sobre", "bolsas", "empaque", "empaques"],
  },
  {
    id: 126,
    label: "Bolsa Ecommerce 20x30cm",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 90,
      },
      prices_qtts: {
        "1": 90,
        "25": 70,
        "50": 60,
      },
      update: "29/8/25",
    },
    measures: {
      ancho: 20,
      alto: 35,
    },
    caracteristicas: ["Con adhesivo"],
    especificaciones: {
      color: "negro",
      grosor: "60 micrones",
    },
    description: "Solapa de 5cm",
    tags: ["sobre", "bolsas", "empaque", "empaques"],
  },
  {
    id: 127,
    label: "Caja Cartón 12.5x11.4x5cm",
    categorie: ["otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 240,
      },
      prices_qtts: {
        "1": 240,
        "10": 200,
      },
      update: "29/8/25",
    },
    measures: {
      largo: 12.5,
      ancho: 11.4,
      alto: 5,
      grosor: 4,
    },
    caracteristicas: ["Desarmada"],
    especificaciones: {
      material: "cartón corrugado",
      "Medida interna": "11.9x10.9x4.9cm",
    },
    tags: ["ecommerce", "packaging", "cajas", "empaque", "empaques"],
  },
  {
    id: 128,
    label: "15x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "boton"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1070,
      },
      prices_qtts: {
        "1": 1070,
        "20": 1010,
        "40": 900,
        "80": 780,
        "200": 730,
      },
      update: "21/4/2025",
    },
    measures: {
      largo: 15,
      alto: 3,
      peso: 4,
      fuerzaExp: 4.3,
    },
    isComparable: true,
  },
  {
    id: 129,
    label: "18x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "boton"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1650,
      },
      prices_qtts: {
        "1": 1650,
        "10": 1550,
        "25": 1390,
        "50": 1210,
        "120": 1140,
      },
      update: "28/8/2025",
    },
    measures: {
      largo: 18,
      alto: 3,
      peso: 6,
      fuerzaExp: 6.3,
    },
    isComparable: true,
  },
  {
    id: 130,
    label: "20x10x2mm",
    categorie: ["imanes", "neodimio"],
    forma: ["rectangular", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 1550,
      },
      prices_qtts: {
        "1": 1550,
        "10": 1460,
        "25": 1290,
        "50": 1120,
        "120": 1050,
      },
      update: "8/9/2025",
    },
    measures: {
      largo: 20,
      ancho: 10,
      alto: 2,
      peso: 2.1,
      fuerzaExp: 3.8,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N45",
    },
  },
  {
    id: 131,
    label: "7x7x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["cuadrado", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 600,
      },
      prices_qtts: {
        "1": 600,
        "25": 570,
        "50": 500,
        "100": 435,
        "250": 410,
        "500": 385,
      },
      update: "28/8/2025",
    },
    measures: {
      largo: 7,
      ancho: 7,
      alto: 3,
      peso: 1.14,
    },
    isComparable: true,
  },
  {
    id: 132,
    label: "8x8x3mm",
    categorie: ["imanes", "neodimio"],
    forma: ["cuadrado", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 600,
      },
      prices_qtts: {
        "1": 600,
        "25": 570,
        "50": 500,
        "100": 435,
        "250": 410,
        "500": 385,
      },
      update: "28/8/2025",
    },
    measures: {
      largo: 8,
      ancho: 8,
      alto: 3,
      peso: 1.43,
      fuerzaExp: 0.9,
    },
    isComparable: true,
  },
  {
    id: 133,
    label: "3x1.5mm",
    categorie: ["imanes", "neodimio"],
    forma: ["redondo", "plano"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 130,
      },
      update: "8/9/2025",
      prices_qtts: {
        "1": 130,
        "25": 120,
        "50": 110,
        "100": 95,
        "500": 90,
        "1000": 85,
      },
    },
    measures: {
      largo: 3,
      alto: 1.5,
    },
    isComparable: true,
    especificaciones: {
      denominación: "N38",
    },
  },
  {
    id: 134,
    label: "Imán Telescópico Extensible",
    categorie: ["imanes", "otros"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 8000,
      },
      update: "13/9/2025",
    },
    measures: {
      largo: 170,
      diametro: 15,
      peso: 300,
    },
    especificaciones: {
      marca: "Salkor",
      modelo: "ITH1600",
      "largo extendido": "61.5cm",
      fuerza: "1.5kg",
    },
    tags: ["lapiz", "pesca", "tuercas", "herramienta", "herramientas"],
  },
  {
    id: 135,
    label: "Set barras de neodimio y esferas",
    categorie: ["imanes", "otrosImanes"],
    price_data: {
      usePrice: "base",
      prices: {
        base: 16000,
      },
      update: "13/9/2025",
    },
    description:
      "Juego de 25 imanes de neodimio de 5x20mm y 30 esferas de acero de 8mm de diámetro.",
    tags: ["juguetes"],
  },
];
